#!/bin/bash
set -e

init() {
  $([[ $1 == "" ]] && echo ./scripts/help uninstall || echo run $@)
  printf "%s\nuninstall complete.\n"
  exit 0
}

run() {
  for cmd in $@; do $cmd; done
}

#/ homebrews       Uninstalls core homebrew kegs
homebrews() {
  printf "%Removing homebrews..\n"
  brew uninstall bash-completion ctags git hub gpg macvim rbenv ruby-build ripgrep tidy-html5 tree watchman wget yarn
}

#/ bash            Removes .bash_profile, .bashrc and .inputrc
bash() {
  for file in "bash_profile" "bashrc" "inputrc"; do
    rm -v $HOME/.$file
  done
}

#/ dots            Removes ~/ .gemrc .gitconfig .gitignore .bundle/
dots() {
  rm -rfv $HOME/.bundle
  for file in "gemrc" "gitconfig" "gitignore"; do
    rm -v $HOME/.$file
  done
}

#/ locals          Removes ~/ .gitconfig.local
locals() {
  for file in "gitconfig"; do
    rm -v $HOME/.$file.local
  done
}

#/ node            Removes ~/ .node-gyp/ .npm/ .nvm/
node() {
  rm -rfv $HOME/.node-gyp/
  rm -rfv $HOME/.npm/
  rm -rfv $HOME/.nvm/
}

#/ ruby            Removes all rubies installed through rbenv
ruby() {
  rm -rfv `rbenv root`
}

#/ gems            Uninstalls all gems and their dependencies
gems() {
  gem list | cut -d" " -f1 | sort | xargs -n1 gem uninstall -aIx
}

#/ vim             Removes .vimrc, .vim/
vim() {
  rm -v $HOME/.vimrc
  rm -rfv $HOME/.vim
}

#/ xcode           Uninstalls custom Xcode files
xcode() {
  rm -rfv $HOME/Library/Developer/Xcode/UserData/FontAndColorThemes
}

#/ casks           Uninstalls non App Store Mac applications
casks() {
  printf "%sRemoving homebrew casks..\n"
  brew cask uninstall appcleaner backblaze charles dropbox firefox google-chrome imageoptim shiftit screenhero sketch
}

#/ world           Runs all of the uninstall commands
world() {
  casks
  xcode
  vim
  gems
  ruby
  node
  homebrews
  locals
  dots
  bash
  printf "%sRemove any remaining dotfiles from the home directory\n"
}

# go..
init $@
