#!/bin/bash
set -e

init() {
  $([[ $1 == "" ]] && echo ./scripts/help uninstall || echo run $@)
  printf "%s\nuninstall complete.\n"
  exit 0
}

run() {
  for cmd in $@; do $cmd; done
}

#/ homebrews       Uninstalls core homebrew kegs
homebrews() {
  printf "%Removing homebrews..\n"
  brew uninstall bash-completion ctags git git-standup heroku hub macvim ripgrep tidy-html5 tree watchman wget yarn
}

#/ bash            Removes .bash_profile, .bashrc and .inputrc
bash() {
  for file in "bash_profile" "bashrc" "inputrc"; do
    rm -v $HOME/.$file
  done
}

#/ dots            Removes ~/ .gitconfig .gitignore
dots() {
  for file in "gitconfig" "gitignore"; do
    rm -v $HOME/.$file
  done
}

#/ locals          Removes ~/ .gitconfig.local
locals() {
  for file in "gitconfig"; do
    rm -v $HOME/.$file.local
  done
}

#/ node            Removes ~/ .node-gyp/ .npm/ .nvm/
node() {
  rm -rfv $HOME/.node-gyp/
  rm -rfv $HOME/.npm/
  rm -rfv $HOME/.nvm/
}

#/ vim             Removes .vimrc, .vim/
vim() {
  rm -v $HOME/.vimrc
  rm -rfv $HOME/.vim
}

#/ casks           Uninstalls non App Store Mac applications
casks() {
  printf "%sRemoving homebrew casks..\n"
  brew cask uninstall appcleaner backblaze charles google-chrome gpgtools imageoptim rowanj-gitx shiftit screenhero sketch qlstephen zeplin
}

#/ world           Runs all of the uninstall commands
world() {
  casks
  vim
  node
  homebrews
  locals
  dots
  bash
  printf "%sRemove any remaining dotfiles from the home directory\n"
}

# go..
init $@
