#!/bin/bash
set -e

init() {
  $([[ $1 == "" ]] && echo ./scripts/help update || echo run $@)
  printf "%s\nupdate complete.\n"
  exit 0
}

run() {
  for cmd in $@; do $cmd; done
}

## Public

#/ homebrews       Updates all programs installed through homebrew / cask
homebrews() {
  printf "%sUpdating homebrew..\n"
  brew update
  brew outdated
  brew upgrade
  brew cleanup
  brew prune
  brew doctor
  brew cask doctor
}

#/ packages        Updates global npm packages
packages() {
  printf "%sUpdating global npm packages..\n"
  npm upgrade --global
}

#/ vim             Message instructions to update the Vim plugins
vim() {
  printf "%s-----------------------------------\n"
  printf "%sUpdate Vim plugins:\n"
  printf "%sPlugUpgrade, PlugUpdate, PlugClean!\n"
  printf "%s-----------------------------------\n"
}

#/ world           Runs all of the update commands
world() {
  homebrews
  packages
  vim
  printf "%Done.\n"
}

# go..
init $@
